name: crypto_coins_list
description: "Cool crypto project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.10+1
  dio: ^5.7.0
  get_it: ^8.0.0
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5
  talker_flutter: ^4.4.1
  talker_dio_logger: ^4.4.1
  talker_bloc_logger: ^4.4.1
  firebase_core: ^3.6.0
  json_annotation: ^4.9.0
  hive_flutter: ^1.1.0
  auto_route: ^9.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  json_serializable: ^6.9.0
  hive_generator: ^2.0.1
  auto_route_generator: ^9.0.0
  build_runner: 

flutter:

  uses-material-design: true

  assets:
   - assets/svg/

