// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATZNwGnYN3N0CChtrF5xeA6js1OGc1PJg',
    appId: '1:11781774594:web:00cd5865133bab617d361b',
    messagingSenderId: '11781774594',
    projectId: 'currency-app-75ebe',
    authDomain: 'currency-app-75ebe.firebaseapp.com',
    storageBucket: 'currency-app-75ebe.appspot.com',
    measurementId: 'G-0FH6YQ6YYZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDs9DhpbDpky8I55AUsgYxfufzWvZ9QEI',
    appId: '1:11781774594:android:101fda9c67c1f5017d361b',
    messagingSenderId: '11781774594',
    projectId: 'currency-app-75ebe',
    storageBucket: 'currency-app-75ebe.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAh0pTgIq-Snrjv64js126JBfqw1_HoOr4',
    appId: '1:11781774594:ios:9fe707e074210bc97d361b',
    messagingSenderId: '11781774594',
    projectId: 'currency-app-75ebe',
    storageBucket: 'currency-app-75ebe.appspot.com',
    iosBundleId: 'com.cryptoguys.cryptoCoinsList',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAh0pTgIq-Snrjv64js126JBfqw1_HoOr4',
    appId: '1:11781774594:ios:9fe707e074210bc97d361b',
    messagingSenderId: '11781774594',
    projectId: 'currency-app-75ebe',
    storageBucket: 'currency-app-75ebe.appspot.com',
    iosBundleId: 'com.cryptoguys.cryptoCoinsList',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyATZNwGnYN3N0CChtrF5xeA6js1OGc1PJg',
    appId: '1:11781774594:web:d8689c87e4a7d8bb7d361b',
    messagingSenderId: '11781774594',
    projectId: 'currency-app-75ebe',
    authDomain: 'currency-app-75ebe.firebaseapp.com',
    storageBucket: 'currency-app-75ebe.appspot.com',
    measurementId: 'G-5NYJNYC6FR',
  );
}
